### PR TITLE
Fixes problems with warnings and multiple calls to asserted value

### LINKED ISSUE #1: Unexpected behaviour
Hello,

I'm curious if it's intentional behaviour that condition check inside `eventually` triggered at least twice even if the first call of it yields a successful result?

To demonstrate this I tweaked one of your tests:
```
    test "when match is successful from the first try" do
      {:ok, mock} =
        start_supervised(
          {MockOperation, [success_return: :ok, failure_return: :error, fail_times: 0]}
        )

      returne_value = assert_eventually :ok = MockOperation.do_something(mock), :ok

      assert returne_value == :ok

      stats = MockOperation.get_stats(mock)
      # by default there should be one call each 20ms
      assert stats.call_counter ==  1
    end
```
This test will fail as call_counter is gonna be equal `2` and not `1` even though the condition was met after the first call of eventually "block".

I looked through the tests and my guess is that you might have thought of scenarios when the state eventually settles and the assertion yields the same results from one point onward. But imagine the scenario when you getting messages from the queue and you are not sure whether the message is ready to be consumed or delay is required. `assert_eventually` looks like the right tool for this job, right? Wrong! If it's just one message and it's ready to be consumed by the time of the first call, it's gonna fetch it with the first call and will fail ugly later on even though the condition of assertion was met. This behaviour is unexpected and it took me some time to figure why my test fails as the matcher basically breaks the expectation of how it should behave. 

Would it be possible to change that so `assert_eventually` would be useful in the scenario I described as well?

### LINKED ISSUE #2: [bug] Warnings on assignments while using eventually macro
Consider this test:

```elixir
   test "hello world" do
    eventually assert variable = Module.hello()
    assert :world == variable
  end
```

If you compile this on Elixir 1.11+ you get this warning:

```
Compiling 1 file (.ex)
Generated eventually_variable app
warning: variable "variable" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/eventually_variable_test.exs:8: EventuallyVariableTest."test get meaningful value by using normal assert"/1

..

Finished in 0.05 seconds
1 doctest, 1 test, 0 failures

Randomized with seed 920761
```

Obviously the variable is used later in the assert, but the compiler doesn't see that.

### PR DESCRIPTION
**Pull request by kelostrada**
Fixes #1 
Fixes #2

### CODE REVIEW

File: lib/assert_eventually.ex [hunk 1]
```diff
@@ -110,6 +110,35 @@ defmodule AssertEventually do
     eventually_impl(assert_call, [], args, timeout)
   end
 
+  defp eventually_impl(assert_call, meta, [{:=, opts, [variable, rest]}], timeout) do
+    ignored_variable = neutralize_variable(variable)
+    neutral_assignment_ast = [{:=, opts, [ignored_variable, {:result, [], AssertEventually}]}]
```
Comment (rslota) [inline lib/assert_eventually.ex]: Is there any reason we're matching with `result` variable instead of actual `rest` expression? I haven't tested this manually, but I think this implementation doesn't work with `assert_raise` because of that.

**Review by rslota — COMMENTED** [review]
Thanks a lot for this PR! Let's try to answer the one question I have and merge this ;)

File: lib/assert_eventually.ex (hunk 1 above)
Comment (rslota) [reply lib/assert_eventually.ex]: Actually, `assert_raise` makes no sense along with this use case, but the original question still stands even if this is just my curiosity.

Comment (rslota) [reply lib/assert_eventually.ex]: I just tested this locally with `neutral_assignment_ast = [{:=, opts, [ignored_variable, rest]}]` and it seems to work just fine while simplifying the code.

Comment (kelostrada) [reply lib/assert_eventually.ex]: I think you are right, it is unnecessary :) It's a leftover from me trying to make the code run the right side of assertion just once (#1) but it was solved actually differently. Let me try quickly to fix it (and write a test to check that this is called just once as well).

Comment (kelostrada) [reply lib/assert_eventually.ex]: done a6411e9

File: lib/assert_eventually.ex [hunk 2]
```diff
@@ -123,15 +148,63 @@ defmodule AssertEventually do
...
+
+    if String.starts_with?(string_value, "_") do
+      {atom, meta, module}
+    else
+      {:"_#{string_value}", meta, module}
+    end
+  end
+
+  # base values
+  defp neutralize_variable(variable), do: variable
```
Comment (kelostrada) [inline lib/assert_eventually.ex:206]: I'm a bit worried about this part - if this handles all the cases. Honestly I think this probably doesn't handle all the cases, but we can always add them if we approach them. Also I'm not super confident about AST representation of structs - I think they are always a list of two tuples - one with `:__aliases__` and the other with the map that is underneath, but I couldn't find anything in docs to confirm that.

**Review by rslota — APPROVED** [review]
Thanks a lot for this PR, that helps a lot! LGTM in general. There is some code duplication now, but I'm not sure how easy it is to get rid of it, so I'm gonna deal with that myself if it's a simple thing to do 🤷 

I'll make a release with those changes very soon.

File: lib/assert_eventually.ex (hunk 2 above)
Comment (rslota) [reply lib/assert_eventually.ex:206]: This is also why I initially leaned towards suppressing warnings here instead if possible. But I think this is fine - if this is a breaking change it's gonna be possible to pin the older version until specific issue is resolved.

**Comment by rslota** [comment]
@kelostrada FYI those changes + small cleanup have been released on hex as `0.3.0`.
